version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_v3
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - certbot
    command: >
      /bin/sh -c "while [ ! -f /etc/letsencrypt/live/${DOMAIN_NAME}/fullchain.pem ]; do sleep 2; done && nginx -g 'daemon off;'"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      /bin/sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot --email ${SSL_EMAIL} --agree-tos --no-eff-email --force-renewal -d ${DOMAIN_NAME} && exit 0"
