version: '3.8'

services:
  traefik:
    image: "traefik:v2.10"
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
      - "--log.level=INFO"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
    volumes:
      - traefik_data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  coolify:
    image: coollabsio/coolify:latest
    container_name: coolify
    restart: unless-stopped
    depends_on:
      - traefik
    networks:
      - proxy
    volumes:
      - coolify_data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coolify.rule=Host(`coolify.${DOMAIN_NAME}`)"
      - "traefik.http.routers.coolify.entrypoints=websecure"
      - "traefik.http.routers.coolify.tls=true"
      - "traefik.http.routers.coolify.tls.certresolver=mytlschallenge"

networks:
  proxy:
    driver: bridge

volumes:
  traefik_data:
    external: true
  coolify_data:
    external: true
