version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.template.conf:/etc/nginx/nginx.template.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - certbot
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    entrypoint: >
      /bin/sh -c "
      envsubst '$$DOMAIN_NAME' < /etc/nginx/nginx.template.conf > /etc/nginx/nginx.conf && 
      while [ ! -f /etc/letsencrypt/live/${DOMAIN_NAME}/fullchain.pem ]; do sleep 2; done && 
      nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      /bin/sh -c "certbot certonly --webroot --
