services:
  nginx:
    image: nginx:latest
    container_name: nginx_v4
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.template.conf:/etc/nginx/nginx.template.conf:ro
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    entrypoint:
      - /bin/sh
      - -c
      - |
        envsubst '$$DOMAIN_NAME' < /etc/nginx/nginx.template.conf > /etc/nginx/nginx.conf
        while [ ! -f /etc/letsencrypt/live/${DOMAIN_NAME}/fullchain.pem ]; do sleep 2; done
        nginx -g 'daemon off;'
